/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/brito/Dev/refactory/apps/web/public/models/kaykit/basemodule_A.gltf --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    basemodule_A: THREE.Mesh
  }
  materials: {
    spacebits_texture: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/basemodule_A.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.basemodule_A.geometry} material={materials.spacebits_texture} />
    </group>
  )
}

useGLTF.preload('/basemodule_A.gltf')
