/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/electric-towers.gltf --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Tower_6_1: THREE.Mesh
    Tower_6_2: THREE.Mesh
    Tower_7_1: THREE.Mesh
    Tower_7_2: THREE.Mesh
    Tower_8_1: THREE.Mesh
    Tower_8_2: THREE.Mesh
    Tower_9_1: THREE.Mesh
    Tower_9_2: THREE.Mesh
    Tower_10_1: THREE.Mesh
    Tower_10_2: THREE.Mesh
    Tower_1_1: THREE.Mesh
    Tower_1_2: THREE.Mesh
    Tower_2_1: THREE.Mesh
    Tower_2_2: THREE.Mesh
    Tower_3_1: THREE.Mesh
    Tower_3_2: THREE.Mesh
    Tower_4_1: THREE.Mesh
    Tower_4_2: THREE.Mesh
    Tower_5_1: THREE.Mesh
    Tower_5_2: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/electric-towers.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[6, 9.269, -0.048]}>
        <mesh geometry={nodes.Tower_6_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Tower_6_2.geometry} material={materials.Material} />
      </group>
      <group position={[12, 9.269, -0.048]}>
        <mesh geometry={nodes.Tower_7_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Tower_7_2.geometry} material={materials.Material} />
      </group>
      <group position={[18, 9.269, -0.048]}>
        <mesh geometry={nodes.Tower_8_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Tower_8_2.geometry} material={materials['Material.001']} />
      </group>
      <group position={[24.638, 9.115, -0.042]}>
        <mesh geometry={nodes.Tower_9_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Tower_9_2.geometry} material={materials.Material} />
      </group>
      <group position={[24.862, 0.015, -0.042]}>
        <mesh geometry={nodes.Tower_10_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Tower_10_2.geometry} material={materials.Material} />
      </group>
      <group position={[6, 0, 0]}>
        <mesh geometry={nodes.Tower_2_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Tower_2_2.geometry} material={materials.Material} />
      </group>
      <group position={[12, 0, 0]}>
        <mesh geometry={nodes.Tower_3_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Tower_3_2.geometry} material={materials.Material} />
      </group>
      <group position={[18, 0, 0]}>
        <mesh geometry={nodes.Tower_4_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Tower_4_2.geometry} material={materials.Material} />
      </group>
      <group position={[0, 9.269, -0.048]} scale={1.074}>
        <mesh geometry={nodes.Tower_5_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Tower_5_2.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Tower_1_1.geometry} material={materials.Material} />
      <mesh geometry={nodes.Tower_1_2.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/electric-towers.gltf')
