/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /Users/brito/Dev/refactory/apps/web/public/models/kaykit/roofmodule_cargo_A.gltf --types 
*/

import { useGLTF } from "@react-three/drei";
import type { ThreeElements } from "@react-three/fiber";
import { Mesh, MeshStandardMaterial } from "three";

export function Model(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF("/roofmodule_cargo_A.gltf");
  const node = nodes.roofmodule_cargo_A;
  const material = materials.spacebits_texture;

  if (!(node instanceof Mesh) || !(material instanceof MeshStandardMaterial)) {
    return null;
  }

  return (
    <group {...props} dispose={null}>
      <mesh geometry={node.geometry} material={material} />
    </group>
  );
}

useGLTF.preload("/roofmodule_cargo_A.gltf");
