import { Effect, Option } from "effect";
import { isPortalHandoff, parsePortalParams } from "./portal";

export type UsernameSource = "query" | "configured" | "auto-generated";

export type ResolvedUsername = {
  readonly source: UsernameSource;
  readonly value: string;
};

type ResolveUsernameOptions = {
  readonly allowAutoGenerated: boolean;
  readonly autoGeneratedUsername: string;
  readonly configuredUsername?: string | null;
  readonly queryUsername?: string | null;
};

type ResolveActorDisplayNameOptions = ResolveUsernameOptions & {
  readonly defaultUsername: string;
};

export const normalizeUsername = Effect.fn("web.username.normalize")(function* (
  value: string | null | undefined,
) {
  return Option.getOrUndefined(
    Option.filter(Option.fromNullishOr(value?.trim()), (trimmed) =>
      trimmed.length > 0
    ),
  );
});

export const resolveUsernameByPriority = Effect.fn("web.username.resolve.by_priority")(function* (
  options: ResolveUsernameOptions,
): Effect.fn.Return<ResolvedUsername | undefined> {
  const queryUsername = yield* normalizeUsername(options.queryUsername);
  const configuredUsername = yield* normalizeUsername(options.configuredUsername);
  const autoGeneratedUsername = yield* normalizeUsername(
    options.autoGeneratedUsername,
  );
  const preferred = Option.map(
    Option.fromUndefinedOr(queryUsername),
    (value): ResolvedUsername => ({ source: "query", value }),
  ).pipe(
    Option.orElse(() =>
      Option.map(
        Option.fromUndefinedOr(configuredUsername),
        (value): ResolvedUsername => ({ source: "configured", value }),
      ),
    ),
    Option.orElse(() =>
      options.allowAutoGenerated
        ? Option.map(
            Option.fromUndefinedOr(autoGeneratedUsername),
            (value): ResolvedUsername => ({
              source: "auto-generated",
              value,
            }),
          )
        : Option.none<ResolvedUsername>(),
    ),
  );

  return Option.getOrUndefined(preferred);
});

export const resolveActorDisplayName = Effect.fn("web.username.resolve.actor_display_name")(function* (
  options: ResolveActorDisplayNameOptions,
): Effect.fn.Return<string> {
  const resolvedUsername = yield* resolveUsernameByPriority(options);
  return resolvedUsername?.value ?? options.defaultUsername;
});

export const readPortalQueryUsername = Effect.fn("web.username.read.portal_query_username")(function* (
  locationSearch: string,
): Effect.fn.Return<string | undefined> {
  const searchParams = new URLSearchParams(locationSearch);
  const portalUsername = Option.getOrUndefined(
    Option.map(
      Option.filter(Option.some(searchParams), isPortalHandoff),
      (params) => parsePortalParams(params).username,
    ),
  );

  return yield* normalizeUsername(portalUsername);
});
