import { expect, test } from "bun:test";
import { Effect } from "effect";
import {
  readPortalQueryUsername,
  resolveActorDisplayName,
  resolveUsernameByPriority,
} from "../src/usernameResolution";

test("query username has highest priority", () => {
  const resolved = Effect.runSync(
    resolveUsernameByPriority({
      allowAutoGenerated: true,
      autoGeneratedUsername: "Auto User",
      configuredUsername: "Configured User",
      queryUsername: "Portal User",
    }),
  );

  expect(resolved).toEqual({
    source: "query",
    value: "Portal User",
  });
});

test("configured username is used when no query username is present", () => {
  const resolved = Effect.runSync(
    resolveUsernameByPriority({
      allowAutoGenerated: true,
      autoGeneratedUsername: "Auto User",
      configuredUsername: "Configured User",
      queryUsername: "   ",
    }),
  );

  expect(resolved).toEqual({
    source: "configured",
    value: "Configured User",
  });
});

test("auto-generated username is only used when allowed", () => {
  const withoutAuto = Effect.runSync(
    resolveUsernameByPriority({
      allowAutoGenerated: false,
      autoGeneratedUsername: "Auto User",
      configuredUsername: undefined,
      queryUsername: undefined,
    }),
  );
  const withAuto = Effect.runSync(
    resolveUsernameByPriority({
      allowAutoGenerated: true,
      autoGeneratedUsername: "Auto User",
      configuredUsername: undefined,
      queryUsername: undefined,
    }),
  );

  expect(withoutAuto).toBeUndefined();
  expect(withAuto).toEqual({
    source: "auto-generated",
    value: "Auto User",
  });
});

test("portal query username is read only for portal handoffs", () => {
  expect(
    Effect.runSync(readPortalQueryUsername("?portal=true&username=Operator")),
  ).toBe("Operator");
  expect(
    Effect.runSync(readPortalQueryUsername("?ref=prev.example&username=Guide")),
  ).toBe("Guide");
  expect(Effect.runSync(readPortalQueryUsername("?username=Ignored"))).toBe(
    undefined,
  );
});

test("default username is used when auto-generated is disabled and no username exists", () => {
  const resolved = Effect.runSync(
    resolveActorDisplayName({
      allowAutoGenerated: false,
      autoGeneratedUsername: "Auto User",
      configuredUsername: undefined,
      defaultUsername: "Operator",
      queryUsername: undefined,
    }),
  );

  expect(resolved).toBe("Operator");
});
